services:
  azpin-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: azpin-backend:latest
    container_name: azpin-backend
    restart: unless-stopped
    environment:
      PORT: "5174"
      SUPABASE_URL: "https://qmrchngwatxrnnkklfwa.supabase.co"
      SUPABASE_ANON_KEY: "sb_publishable_FHdYeBLA59RTUx1SVtbBrQ__L35Ax02"
      SUPABASE_SERVICE_ROLE_KEY: "sb_publishable_FHdYeBLA59RTUx1SVtbBrQ__L35Ax02"
      HUBMSG_API_KEY: "API-KEY-XXXX"
    volumes:
      - /datastore/azpin/uploads:/app/public/uploads
    networks:
      - internal

  azpin-frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        VITE_SUPABASE_URL: "https://qmrchngwatxrnnkklfwa.supabase.co"
        VITE_SUPABASE_ANON_KEY: "sb_publishable_FHdYeBLA59RTUx1SVtbBrQ__L35Ax02"
    image: azpin-frontend:latest
    container_name: azpin-frontend
    restart: unless-stopped
    environment:
      VITE_SUPABASE_URL: "https://qmrchngwatxrnnkklfwa.supabase.co"
      VITE_SUPABASE_ANON_KEY: "sb_publishable_FHdYeBLA59RTUx1SVtbBrQ__L35Ax02"
    volumes:
      - /datastore/azpin/nginx-logs:/app/nginx-logs
    networks:
      - internal
      - edge
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=edge'
      - 'traefik.http.routers.azpin.rule=Host(`azpinx.com`) || Host(`azpinx.octotech.az`)'
      - 'traefik.http.routers.azpin.entrypoints=web'
      - 'traefik.http.services.azpin.loadbalancer.server.port=80'

networks:
  edge:
    external: true
  internal:
    driver: bridge
