services:
  azpin-db:
    image: mysql:8.0
    container_name: azpin-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: azpin_db
      MYSQL_USER: azpin_user
      MYSQL_PASSWORD: azpin_pass
      MYSQL_ROOT_PASSWORD: azpin_root_pass
    volumes:
      - /datastore/azpin/mysql:/var/lib/mysql
    networks:
      - internal

  azpin-backend:
    image: azpin-backend:latest
    pull_policy: never
    container_name: azpin-backend
    restart: unless-stopped
    depends_on:
      - azpin-db
    environment:
      PORT: "5174"
      DB_HOST: azpin-db
      DB_USER: azpin_user
      DB_PASSWORD: azpin_pass
      DB_NAME: azpin_db
      JWT_SECRET: "azpin-super-secret-key"
      HUBMSG_API_KEY: "API-KEY-XXXX"
    volumes:
      - /datastore/azpin/uploads:/app/public/uploads
    networks:
      - internal

  azpin-frontend:
    image: azpin-frontend:latest
    pull_policy: never
    container_name: azpin-frontend
    restart: unless-stopped
    depends_on:
      - azpin-backend
    networks:
      - internal
      - edge
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=edge'
      - 'traefik.http.routers.azpin.rule=Host(`azpinx.octotech.az`) || Host(`azpinx.az`) || Host(`azpinx.com`)'
      - 'traefik.http.routers.azpin.entrypoints=web'
      - 'traefik.http.services.azpin.loadbalancer.server.port=80'
    volumes:
      - /datastore/azpin/nginx-logs:/app/nginx-logs

networks:
  edge:
    external: true
  internal:
    driver: bridge
